"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
		DEBUG=(bool, True), # Define default values or types for variables
		RENDER_EXTERNAL_HOSTNAME=(str,'127.0.0.1')
)
# Explicitly read .env file from the correct location
env_file_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file_path):
    environ.Env.read_env(env_file_path)
else:
    print(f"Warning: .env file not found at {env_file_path}")


import sys
sys.path.insert(0, str(BASE_DIR.parent))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['jobflex.cl', 'www.jobflex.cl', '179.43.127.166', 'localhost', '127.0.0.1']

# Seguridad de Proxy y SSL
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

CSRF_TRUSTED_ORIGINS = [
    'https://www.jobflex.cl', 
    'https://jobflex.cl',
]


# Application definition

INSTALLED_APPS = [
		'JFlex.apps.JflexConfig',
		'sii.apps.SiiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Added for intcomma filter
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'storages',
    'googleapiclient',
    'django.contrib.sitemaps',
    'compressor',
]

if DEBUG:
    INSTALLED_APPS += ["django_browser_reload"]

SITE_ID = 1

# Configuracion de Allauth
LOGIN_REDIRECT_URL = '/user_index/'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_USERNAME_REQUIRED = False # Allow signup without asking for username
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = 'JFlex.adapters.CustomSocialAccountAdapter'

# Obligar a que los links de login social sean siempre HTTPS
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
#CAMBIAR CONFIGURACION DE GOOGLE DE URIs DE REDIRECCION CUANDO SE ESTE EN PRODUCCION
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('CLIENT_ID'), 
            'secret': env('SECRET'), 
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'consent',
        }
    }
}

# Google Calendar API credentials
GOOGLE_CALENDAR_OAUTH_CLIENT_ID = env('GOOGLE_CALENDAR_OAUTH_CLIENT_ID', default=None)
GOOGLE_CALENDAR_OAUTH_CLIENT_SECRET = env('GOOGLE_CALENDAR_OAUTH_CLIENT_SECRET', default=None)

# The full callback URI needs to be defined here to be used in the auth flow
# NOTE: This will need to be changed for production
GOOGLE_CALENDAR_REDIRECT_URI = 'http://127.0.0.1:8000/google/oauth2callback/'

ACCOUNT_FORMS = {
    'login': 'JFlex.forms.CustomLoginForm',
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
		'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE += ["django_browser_reload.middleware.BrowserReloadMiddleware"]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'JFlex.context_processors.company_context',
                'JFlex.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'django_jobflex',
        'USER': 'admin_jobflex',
        'PASSWORD': env('DB_DEFAULT_PASS'),
        'HOST': 'jobflex-sv.database.windows.net',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;',
        },
    },
    'sii': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jobflex_sii',
        'USER': 'jobflex',
        'PASSWORD': env('DB_SII_PASS'),
        'HOST': '34.176.162.168',
        'PORT': '3306',
    },
    'jflex_db': {
        'ENGINE': 'mssql',
        'NAME': 'jobflex_prod',
        'USER': 'admin_jobflex',
        'PASSWORD': env('DB_JFLEX_PASS'),
        'HOST': 'jobflex-sv.database.windows.net',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;',
        },
    }
}

DATABASE_ROUTERS = ['JFlex.routers.JFlexRouter']



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# else: # Development with local media storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/user_index/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env('EMAIL_PORT', cast=int, default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env('EMAIL_USE_TLS', cast=bool, default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no-reply@jobflex.cl')

AUTHENTICATION_BACKENDS = [
    'JFlex.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# S3 Caching parameters
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_ENABLED = True

