# Generated by Django 5.2.5 on 2025-10-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id_candidato', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidato_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut_candidato', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CVCandidato',
            fields=[
                ('id_cv_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cv', models.CharField(max_length=100)),
                ('cargo_asociado', models.CharField(max_length=100)),
                ('tipo_cv', models.CharField(max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('resumen_empresa', models.TextField(max_length=1000)),
                ('mision', models.TextField(blank=True, max_length=500, null=True)),
                ('vision', models.TextField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='company_banners/')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrevista', models.DateField()),
                ('hora_entrevista', models.TimeField()),
                ('nombre_reclutador', models.CharField(max_length=150)),
                ('modalidad', models.CharField(max_length=20)),
                ('asistencia_confirmada', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_jornada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id_modalidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_modalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('link_relacionado', models.URLField(blank=True, max_length=255, null=True)),
                ('usuario_destino', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolesEmpresa',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion_rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RubroIndustria',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rubro', models.CharField(max_length=50)),
                ('descripcion_rubro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id_tipo_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CVCreado',
            fields=[
                ('id_cv_creado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.cvcandidato')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVSubido',
            fields=[
                ('id_cv_subido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.cvcandidato')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
                ('ruta_archivo', models.FileField(upload_to='cv_uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ModoOnline',
            fields=[
                ('id_modo_online', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.entrevista')),
                ('plataforma', models.CharField(max_length=100)),
                ('url_reunion', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModoPresencial',
            fields=[
                ('id_modo_presencial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.entrevista')),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionCandidato',
            fields=[
                ('id_notificacion_candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.notificaciones')),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionEmpresa',
            fields=[
                ('id_notificacion_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.notificaciones')),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_puesto', models.CharField(max_length=150)),
                ('descripcion_puesto', models.TextField(max_length=2000)),
                ('requisitos_puesto', models.TextField(max_length=1000)),
                ('habilidades_clave', models.CharField(blank=True, max_length=500, null=True)),
                ('beneficios', models.CharField(blank=True, max_length=500, null=True)),
                ('nivel_experiencia', models.CharField(max_length=50)),
                ('salario_min', models.IntegerField()),
                ('salario_max', models.IntegerField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.empresa')),
                ('jornada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.jornada')),
                ('modalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado_postulacion', models.CharField(max_length=50)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.candidato')),
                ('cv_postulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.cvcandidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.ofertalaboral')),
            ],
        ),
        migrations.AddField(
            model_name='entrevista',
            name='postulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.postulacion'),
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id_empresa_user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empresa_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.empresa')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.rolesempresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.rubroindustria'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='tipo_notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.tiponotificacion'),
        ),
        migrations.CreateModel(
            name='RegistroUsuarios',
            fields=[
                ('id_registro', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('tipo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.tipousuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.ubicacion'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.ubicacion'),
        ),
        migrations.CreateModel(
            name='DatosPersonalesCV',
            fields=[
                ('id_cv_creado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.cvcreado')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo_profesional', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoProfesionalCV',
            fields=[
                ('id_cv_creado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='JFlex.cvcreado')),
                ('texto_objetivo', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VoluntariadoCV',
            fields=[
                ('id_voluntariado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_organizacion', models.CharField(max_length=100)),
                ('puesto_rol', models.CharField(max_length=100)),
                ('descripcion_actividades', models.TextField(max_length=1000)),
                ('ciudad', models.CharField(max_length=50)),
                ('region_estado_provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('actualmente_activo', models.BooleanField(default=False)),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntariado', to='JFlex.cvcreado')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciasCV',
            fields=[
                ('id_referencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_referente', models.CharField(max_length=100)),
                ('cargo_referente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('url_linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='JFlex.cvcreado')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectosCV',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('fecha_proyecto', models.DateField()),
                ('rol_participacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_proyecto', models.TextField(max_length=1000)),
                ('url_proyecto', models.URLField(blank=True, max_length=255, null=True)),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='JFlex.cvcreado')),
            ],
        ),
        migrations.CreateModel(
            name='IdiomaCV',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_idioma', models.CharField(max_length=50)),
                ('nivel_idioma', models.CharField(max_length=30)),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='JFlex.cvcreado')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadCV',
            fields=[
                ('id_habilidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_habilidad', models.CharField(max_length=50)),
                ('texto_habilidad', models.CharField(max_length=150)),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='JFlex.cvcreado')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboralCV',
            fields=[
                ('id_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_puesto', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('trabajo_actual', models.BooleanField(default=False)),
                ('practica', models.BooleanField(default=False)),
                ('horas_practica', models.IntegerField(blank=True, null=True)),
                ('descripcion_cargo', models.TextField(max_length=1000)),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='JFlex.cvcreado')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionCV',
            fields=[
                ('id_educacion', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=100)),
                ('carrera_titulo_nivel', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('cursando', models.BooleanField(default=False)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='JFlex.cvcreado')),
            ],
        ),
        migrations.CreateModel(
            name='CertificacionesCV',
            fields=[
                ('id_certificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_certificacion', models.CharField(max_length=150)),
                ('entidad_emisora', models.CharField(max_length=150)),
                ('fecha_obtencion', models.DateField()),
                ('cv_creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='JFlex.cvcreado')),
            ],
        ),
    ]
