# Generated by Django 5.2.5 on 2025-10-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrousuarios',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='registrousuarios',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='registrousuarios',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='registrousuarios',
            name='segundo_nombre',
        ),
        migrations.AddField(
            model_name='registrousuarios',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrousuarios',
            name='nombres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
