# Generated by Django 5.2.5 on 2025-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0002_remove_registrousuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='pais',
            field=models.CharField(default='Chile', max_length=100),
        ),
    ]
