# Generated by Django 5.2.5 on 2025-10-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0003_ubicacion_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='pais',
        ),
    ]
