# Generated by Django 5.2.5 on 2025-11-08 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0004_remove_ubicacion_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.empresa')),
            ],
            options={
                'db_table': 'CompanyInvitationToken',
                'managed': True,
            },
        ),
    ]
