# Generated by Django 5.2.5 on 2025-11-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0005_companyinvitationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsubido',
            name='ruta_archivo',
            field=models.URLField(max_length=500),
        ),
    ]
