# Generated by Django 5.2.5 on 2025-11-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0006_alter_cvsubido_ruta_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='activa', max_length=10),
        ),
    ]
