# Generated by Django 5.2.5 on 2025-11-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0006_alter_cvsubido_ruta_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagen_perfil',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen_portada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
