# Generated by Django 5.2.5 on 2025-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0007_ofertalaboral_estado_alter_empresa_imagen_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='activa', max_length=10),
        ),
    ]
