# Generated by Django 5.2.5 on 2025-11-14 06:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_locations_forward(apps, schema_editor):
    """
    Migrates data from the old Ubicacion model to the new Region and Ciudad models.
    Also updates foreign keys in Candidato and Empresa.
    """
    # We get the model from the versioned app registry;
    # if we import it directly, it'll be the wrong version
    Ubicacion = apps.get_model('JFlex', 'Ubicacion')
    Region = apps.get_model('JFlex', 'Region')
    Ciudad = apps.get_model('JFlex', 'Ciudad')
    Candidato = apps.get_model('JFlex', 'Candidato')
    Empresa = apps.get_model('JFlex', 'Empresa')

    db_alias = schema_editor.connection.alias

    # 1. Create Regions and the special "Cualquier comuna" city for each.
    unique_regions = Ubicacion.objects.using(db_alias).values_list('region', flat=True).distinct()
    
    new_regions_map = {}
    for region_name in unique_regions:
        if region_name:  # Ensure the region name is not empty
            region, created = Region.objects.using(db_alias).get_or_create(nombre=region_name)
            new_regions_map[region_name] = region
            
            # Create the special "Cualquier comuna" for this region
            Ciudad.objects.using(db_alias).get_or_create(
                region=region,
                nombre="Cualquier comuna"
            )

    # 2. Create Cities and build a map from old ubicacion_id to new ciudad object
    ubicacion_to_ciudad_map = {}
    for ubicacion in Ubicacion.objects.using(db_alias).all():
        if ubicacion.region in new_regions_map:
            region_obj = new_regions_map[ubicacion.region]
            ciudad, created = Ciudad.objects.using(db_alias).get_or_create(
                region=region_obj,
                nombre=ubicacion.ciudad
            )
            ubicacion_to_ciudad_map[ubicacion.id_ubicacion] = ciudad

    # 3. Update Foreign Keys in Candidato and Empresa
    # We need to handle potential nulls or non-existent old IDs gracefully
    for candidato in Candidato.objects.using(db_alias).filter(ubicacion_id__isnull=False):
        new_ciudad = ubicacion_to_ciudad_map.get(candidato.ubicacion_id)
        if new_ciudad:
            candidato.ciudad_id = new_ciudad.pk
            candidato.save(using=db_alias, update_fields=['ciudad_id'])

    for empresa in Empresa.objects.using(db_alias).filter(ubicacion_id__isnull=False):
        new_ciudad = ubicacion_to_ciudad_map.get(empresa.ubicacion_id)
        if new_ciudad:
            empresa.ciudad_id = new_ciudad.pk
            empresa.save(using=db_alias, update_fields=['ciudad_id'])


def migrate_locations_backward(apps, schema_editor):
    """
    Reverts the migration. This is a destructive operation.
    """
    Region = apps.get_model('JFlex', 'Region')
    Ciudad = apps.get_model('JFlex', 'Ciudad')
    db_alias = schema_editor.connection.alias
    
    Ciudad.objects.using(db_alias).all().delete()
    Region.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0008_ofertalaboral_estado'),
    ]

    operations = [
        # Step 1: Create the new models and their fields
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='JFlex.region')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('nombre', 'region')},
        ),
        # Step 2: Add the new 'ciudad' foreign key to the models that need it.
        # They are temporarily nullable to allow the data migration to run.
        migrations.AddField(
            model_name='candidato',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.ciudad'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JFlex.ciudad'),
        ),
        
        # Step 3: Run the data migration to populate the new tables and FKs
        migrations.RunPython(migrate_locations_forward, migrate_locations_backward),
        
        # Step 4: Remove the old 'ubicacion' foreign key fields
        migrations.RemoveField(
            model_name='candidato',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ubicacion',
        ),
        
        # Step 5: Delete the old 'Ubicacion' model
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
