# Generated by Django 5.2.5 on 2025-11-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0009_ciudad_region_remove_candidato_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='cv_visto',
            field=models.BooleanField(default=False),
        ),
    ]
