# Generated by Django 5.2.5 on 2025-11-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0010_postulacion_cv_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousuarios',
            name='autenticacion_dos_factores_activa',
            field=models.BooleanField(default=False),
        ),
    ]
