# Generated by Django 5.2.5 on 2025-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0011_registrousuarios_autenticacion_dos_factores_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
