# Generated by Django 5.2.5 on 2025-10-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSII',
            fields=[
                ('rut', models.IntegerField(help_text='RUT de la empresa sin el dígito verificador.')),
                ('dv', models.CharField(help_text='Dígito verificador del RUT.', max_length=1)),
                ('razon_social', models.CharField(help_text='Nombre o razón social de la empresa.', max_length=255)),
                ('rut_completo', models.CharField(help_text='RUT completo con guión, ej: 12345678-9.', max_length=12, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa SII',
                'verbose_name_plural': 'Empresas SII',
                'db_table': 'sii_empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
